"""empty message

Revision ID: 164f7bb479d5
Revises:
Create Date: 2017-06-12 16:45:58.735672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '164f7bb479d5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_group',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=120), nullable=False),
                    sa.Column('department', sa.String(
                        length=120), nullable=True),
                    sa.Column('slug', sa.String(length=120), nullable=False),
                    sa.Column('username', sa.String(
                        length=120), nullable=True),
                    sa.Column('created', sa.DateTime(), nullable=True),
                    sa.Column('updated', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_product_group_name'),
                    'product_group', ['name'], unique=True)
    op.create_index(op.f('ix_product_group_slug'),
                    'product_group', ['slug'], unique=True)
    op.create_table('product',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=120), nullable=False),
                    sa.Column('slug', sa.String(length=120), nullable=False),
                    sa.Column('product_group_id',
                              sa.Integer(), nullable=False),
                    sa.Column('username', sa.String(
                        length=120), nullable=True),
                    sa.Column('created', sa.DateTime(), nullable=True),
                    sa.Column('updated', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['product_group_id'], [
                                            'product_group.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_product_name'), 'product', ['name'], unique=True)
    op.create_index(op.f('ix_product_slug'), 'product', ['slug'], unique=True)
    op.create_table('indicator',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=120), nullable=False),
                    sa.Column('source', sa.JSON(), nullable=False),
                    sa.Column('unit', sa.String(length=20), nullable=False),
                    sa.Column('aggregation', sa.String(length=80), nullable=True),
                    sa.Column('product_id', sa.Integer(), nullable=False),
                    sa.Column('slug', sa.String(length=120), nullable=False),
                    sa.Column('username', sa.String(
                        length=120), nullable=True),
                    sa.Column('created', sa.DateTime(), nullable=True),
                    sa.Column('updated', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name', 'product_id',
                                        name='indicator_name_product_id_key')
                    )
    op.create_index(op.f('ix_indicator_name'),
                    'indicator', ['name'], unique=False)
    op.create_index(op.f('ix_indicator_slug'),
                    'indicator', ['slug'], unique=False)
    op.create_table('objective',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('title', sa.Text(), nullable=False),
                    sa.Column('description', sa.Text(), nullable=True),
                    sa.Column('product_id', sa.Integer(), nullable=True),
                    sa.Column('username', sa.String(
                        length=120), nullable=True),
                    sa.Column('created', sa.DateTime(), nullable=True),
                    sa.Column('updated', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['product_id'], ['product.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('indicatorvalue',
                    sa.Column('timestamp', sa.DateTime(), nullable=False),
                    sa.Column('value', sa.Float(), nullable=False),
                    sa.Column('indicator_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['indicator_id'], ['indicator.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint(
                        'timestamp', 'indicator_id', name='indicatorvalue_timestamp_indicator_id_pkey')
                    )
    op.create_table('target',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('target_from', sa.Float(), nullable=True),
                    sa.Column('target_to', sa.Float(), nullable=True),
                    sa.Column('indicator_id', sa.Integer(), nullable=False),
                    sa.Column('objective_id', sa.Integer(), nullable=False),
                    sa.Column('username', sa.String(
                        length=120), nullable=True),
                    sa.Column('created', sa.DateTime(), nullable=True),
                    sa.Column('updated', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['indicator_id'], ['indicator.id'], ),
                    sa.ForeignKeyConstraint(
                        ['objective_id'], ['objective.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('indicator_id', 'objective_id',
                                        name='target_indicator_id_objective_id_key')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('target')
    op.drop_table('indicatorvalue')
    op.drop_table('objective')
    op.drop_index(op.f('ix_indicator_slug'), table_name='indicator')
    op.drop_index(op.f('ix_indicator_name'), table_name='indicator')
    op.drop_table('indicator')
    op.drop_index(op.f('ix_product_slug'), table_name='product')
    op.drop_index(op.f('ix_product_name'), table_name='product')
    op.drop_table('product')
    op.drop_index(op.f('ix_product_group_slug'), table_name='product_group')
    op.drop_index(op.f('ix_product_group_name'), table_name='product_group')
    op.drop_table('product_group')
    # ### end Alembic commands ###
