"""empty message

Revision ID: 76061b80da15
Revises: c8383b83857d
Create Date: 2017-09-27 14:58:50.300927

"""
from alembic import op


# revision identifiers, used by Alembic.
revision = '76061b80da15'
down_revision = 'c8383b83857d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('target_objective_id_fkey', 'target', type_='foreignkey')
    op.create_foreign_key(None, 'target', 'objective', ['objective_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'target', type_='foreignkey')
    op.create_foreign_key('target_objective_id_fkey', 'target', 'objective', ['objective_id'], ['id'])
    # ### end Alembic commands ###
