"""empty message

Revision ID: 883656b7ff4e
Revises: f6f7625d0e47
Create Date: 2018-06-28 12:54:43.100549

"""
from alembic import op


# revision identifiers, used by Alembic.
revision = '883656b7ff4e'
down_revision = 'f6f7625d0e47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_indicator_product_id'), 'indicator', ['product_id'], unique=False)
    op.create_index(op.f('ix_objective_product_id'), 'objective', ['product_id'], unique=False)
    op.create_index(op.f('ix_product_product_group_id'), 'product', ['product_group_id'], unique=False)
    op.create_index(op.f('ix_target_indicator_id'), 'target', ['indicator_id'], unique=False)
    op.create_index(op.f('ix_target_objective_id'), 'target', ['objective_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_target_objective_id'), table_name='target')
    op.drop_index(op.f('ix_target_indicator_id'), table_name='target')
    op.drop_index(op.f('ix_product_product_group_id'), table_name='product')
    op.drop_index(op.f('ix_objective_product_id'), table_name='objective')
    op.drop_index(op.f('ix_indicator_product_id'), table_name='indicator')
    # ### end Alembic commands ###
